object Versions {
    const val coreKtx = "1.9.0"
    const val appCompat = "1.5.1"
    const val activityKtx = "1.5.1"
    const val fragmentKtx = "1.5.2"
    const val navigation = "2.5.2"
    const val koin = "3.2.0"
    const val glide = "4.13.2"
    const val moxy = "2.2.2"
    const val cicerone = "7.1"
    const val okHttpInterceptor = "4.9.2"
    const val retrofit = "2.9.0"
    const val retrofitRx = "3.0.0"
    const val retrofitKotlinxConverter = "0.8.0"
    const val retrofitGsonConverter = "2.9.0"
    const val room = "2.4.3"
    const val rxKotlin = "3.0.1"
    const val rxAndroid = "3.0.0"
    const val kotlinxSerialization = "1.2.0"
    const val splashScreen = "1.0.0"
    const val swipeRefreshLayout = "1.1.0"
    const val junit = "4.13.2"
    const val junitExt = "1.1.3"
    const val espresso = "3.4.0"
    const val material = "1.6.1"
    const val constraintLayout = "2.1.4"
}